version: '3.8'
services:
  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "3010:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: taskdb
      DB_HOST: db        # Docker service name for Postgres
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
